version: v1.0.0

data_root: data

train_dataset: busi
test_datasets: [busi]

epoch: 200
batch_size: 16

print_freq_step: 10
val_freq_epoch: 1

image_size: 224
model_name: ViT-L-14
layers_out: [6,12,18,24]

alpha: 0.5
lr: [0.001,0.001,0.001]

num_clusters: 8
anomaly_tasks:
  CutpasteTask: 0.25
  GaussIntensityChangeTask: 0.25
  SourceTask: 0.25
  IdentityTask: 0.25

prompt_maker: coop
n_learnable_token: 8
CSC: True
class_token_positions: [end]

save_root: results/busi

prompts:
  normal: [
    normal,
    healthy,
    negative,
    unremarkable,
    clear,
    asymptomatic,
    normal findings,
    no findings,
    in good health,
    no evidence of disease
  ]

  abnormal: [
        abnormal,
        positive,
        symptomatic,
        disease,
        lesion,
        pathological,
        impaired,
        evidence of disease,
        abnormal finding,
        pathological condition,
        pathological abnormality
  ]